version: "3.9"

services:
  api:
    build: .
    image: my-flask-postgresql-app
    container_name: flask-postgresql-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://myuser:mypass@db:5432/mydb
      FLASK_SERVER_ENV: development
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: unless-stopped

volumes:
  pgdata:
